name: ubuntu-webapp
version: '1.0'
summary: ubuntu webapp
description: |
  Webapp version of the ubuntu web application.

grade: stable
confinement: devmode

parts:
  webapp-container:
    after: [desktop-ubuntu-app-platform,webapp-helper]
    plugin: nil


